opentsdb:
    image: stackexchange/bosun 
    ports:
    - 8070:8070
    - 4242:4242
    - 60030:60030
    container_name: opentsdb

opentsdb_ddclient:
    image: gitlab.testbed.se:5000/ostdb_client
    container_name: otsdb_ddclient
    links:
    - opentsdb:otsdb
    external_links:
    - ddbroker:dealer
    volumes:
    - /etc/doubledecker:/keys
